---
#Please change the relative directories according to your file locations. 
- name: Assignment2
  
  hosts: webservers
  become: true
  
  tasks:
  - name: Updation apt cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200
      
  - name: nginix uninstall 
    apt:
     name: nginx
     state: absent   
    
  - name: Installing niginx
    become: true
    apt:
      name: nginx
      state: latest   
      
  - name: Creating a directory if not exsits
    become: yes
    file:
     path: /home/A1/site
     state: directory
     mode: '0755'
     
  - name: Deleting nginx.conf file
    file:
     path: /etc/nginx/nginx.conf
     state: absent
     
  - name: Adding nginx.conf with permissions
    become: yes
    copy: 
     src: ./nginx.conf
     dest: /etc/nginx/nginx.conf
     
  

      
      
  - name: starting nginx   
    service:
              name: nginx 
              state: started 
    become: yes
  
  - name: Uninstalling PHP httpd
    apt:
     name: php
     state: absent   
  
  - name: Installing PHP the packages
    become: true
    apt:
      name: php
      state: latest   
      
  - name: Installing PHP7.4 httpd 
    apt:
     name: php7.4-fpm
     state: absent    
  
  - name: Installing the packages
    become: true
    apt:
      name: php7.4-fpm
      state: latest   
###

  - name: De1eting index.php file
    file:
     path: /var/www/html/index.php
     state: absent

  - name: Copying index.php with permissions
    become: yes
    copy: 
     src: ./index.php
     dest: /var/www/html/index.php
     #Installing all the packages

###copying the nginxsdconf file 


  - name: Removing existing default file
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent


  - name: inserting files
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: linking default configuration
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link





   

     
  - name: nginx restart
    service:
       name: nginx
       state: restarted
    become: yes        
  

     
- hosts: all
  gather_facts: y
  
- hosts: haproxy
  become: true
 

  vars:
    haproxy_maxconns: 4096
    haproxy_backlog: 2
    haproxy_timeout_q: 400ms
    haproxy_timoutconnect: 5000ms
    haproxy_timeoutclient: 5000ms
    haproxy_timoutserver: 5000ms
    haproxy_http_timeout: 15s
    haproxy_balance: leastconn
    haproxy_frontend_port: 80


  
  - name: Updation of apt cache 
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200

  - name: Instalation of package 
    become: true
    apt:
      name: haproxy
      state: latest   

  - name: upgrading packages
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
    notify:
      - run Haproxy      

  - name: Getting information of server
    setup:
      filter: ansible_default_ipv4.address   


  - name: To remove existing default haproxy confg file
    file:
       path: "/etc/haproxy/haproxy.cfg"
       state: absent
    notify:
    - restart Haproxy 

  - name: Deploy HAProxy configuration
    template:
      src: ./haproxy
      dest: "/etc/haproxy/haproxy.cfg"
    notify:
      - restart Haproxy
      - run Haproxy

  handlers:

  - name: run Haproxy
    service:
      name: haproxy
      state: started

  - name: restart Haproxy
    service:
      name: haproxy
      state: restarted
      
- hosts: webservers
  gather_facts: y
  
  tasks:
  
  - name: restart nginx
    service:
       name: nginx
       state: restarted
    become: yes









